services:
  db:
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo_network
    # restart: unless-stopped

  odoo:
    image: odoo:15
    env_file: .env
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_PASSWORD: ${ODOO_ADMIN_PASSWORD}
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      
      - ./config:/etc/odoo.conf
    networks:
      - odoo_network
    #restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   depends_on:
  #     - odoo
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   networks:
  #     - odoo_network

volumes:
  postgres_data:
  odoo_data:

networks:
  odoo_network:
    driver: bridge

