services:
  db:
    image: postgres:9.4
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo_network
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 15
    # restart: unless-stopped

  odoo:
    image: odoo:10
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    #command: odoo -i base -d odoo_prod
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ODOO_ADMIN_PASSWORD: ${ODOO_ADMIN_PASSWORD}
    ports:
      - "127.0.0.1:8469:8069" 
      - "127.0.0.1:8470:8070" 
      - "127.0.0.1:8471:8071" 
      - "127.0.0.1:8472:8072" 
    volumes:
      - odoo_data:/var/lib/odoo
      - /home/tony/Documents/Développement/dev_odoo/10.0/locavore/:/mnt/extra-addons
      - /home/tony/Documents/Développement/dev_odoo/10.0/lf2016/:/mnt/extra-addons-lf2016
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo_network
    # restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   depends_on:
  #     - odoo
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   networks:
  #     - odoo_network

volumes:
  postgres_data:
  odoo_data:

networks:
  odoo_network:
    driver: bridge

